name: Vertigo
version: 1.3
main: me.hawkfalcon.Vertigo.Vertigo
permissions: 
     vertigo.use:
        description: Allows use of plugin
        default: true
     vertigo.others:
        description: Allows use of commands tha affect others
        default: OP
     vertigo.all:
        description: Allows use of /vertigo all
        default: OP
        
commands:
    vertigo:
        description: main command
        usage: /vertigo
        
